#!/usr/bin/env python
# coding=utf-8
"""
This file contains regression test_repo automatically generated by
``stbt auto-selftest``. These test_repo are intended to capture the
behaviour of Frame Objects (and other helper functions that operate on
a video-frame). Commit this file to git, re-run ``stbt auto-selftest``
whenever you make a change to your Frame Objects, and use ``git diff``
to see how your changes affect the behaviour of the Frame Object.

NOTE: THE OUTPUT OF THE DOCTESTS BELOW IS NOT NECESSARILY "CORRECT" --
it merely documents the behaviour at the time that
``stbt auto-selftest`` was run.
"""
# pylint: disable=line-too-long

import os
import sys

sys.path.insert(0, os.path.join(
    os.path.dirname(__file__), '../../../test_repo'))

from dialogs import *  # isort:skip pylint: disable=wildcard-import, import-error

_FRAME_CACHE = {}


def f(name):
    img = _FRAME_CACHE.get(name)
    if img is None:
        import cv2
        filename = os.path.join(os.path.dirname(__file__),
                                '../../screenshots', name)
        img = cv2.imread(filename)
        assert img is not None, "Failed to load %s" % filename
        img.flags.writeable = False
        _FRAME_CACHE[name] = img
    return img


def auto_selftest_ConfirmRentalDialog():
    r"""
    >>> ConfirmRentalDialog(frame=f("Worldbox/Video Store/Confirm Rental - Cancel.png"))
    ConfirmRentalDialog(is_visible=True, selection=u'CANCEL')
    >>> ConfirmRentalDialog(frame=f("Worldbox/Video Store/Confirm Rental - Confirm.png"))
    ConfirmRentalDialog(is_visible=True, selection=u'CONFIRM')
    """
    pass


def auto_selftest_ExitDialog():
    r"""
    >>> ExitDialog(frame=f("Worldbox/Video Store/Exit.png"))
    ExitDialog(is_visible=True)
    """
    pass


def auto_selftest_ModalDialog():
    r"""
    """
    pass


def auto_selftest_SelectedButton():
    r"""
    >>> SelectedButton(frame=f("New box/Still There.png"))
    SelectedButton(is_visible=True, text=u'DISMISS')
    >>> SelectedButton(frame=f("New box/Video Store/Unable to Play.png"))
    SelectedButton(is_visible=True, text=u'OK')
    >>> SelectedButton(frame=f("Worldbox/Video Store/Asset - Moonlight - Rent.png"))
    SelectedButton(is_visible=True, text=u'RENT $2.99')
    >>> SelectedButton(frame=f("Worldbox/Video Store/Asset - Moonlight - Restart.png"))
    SelectedButton(is_visible=True, text=u'RESTART')
    >>> SelectedButton(frame=f("Worldbox/Video Store/Asset - Moonlight - Watch.png"))
    SelectedButton(is_visible=True, text=u'WATCH')
    >>> SelectedButton(frame=f("Worldbox/Video Store/Asset - Rogue One.png"))
    SelectedButton(is_visible=True, text=u'RENT $2.99')
    >>> SelectedButton(frame=f("Worldbox/Video Store/Confirm Rental - Cancel.png"))
    SelectedButton(is_visible=True, text=u'CANCEL')
    >>> SelectedButton(frame=f("Worldbox/Video Store/Confirm Rental - Confirm.png"))
    SelectedButton(is_visible=True, text=u'CONFIRM')
    """
    pass


def auto_selftest_StillThereDialog():
    r"""
    >>> StillThereDialog(frame=f("New box/Still There.png"))
    StillThereDialog(is_visible=True)
    """
    pass


def auto_selftest_UnableToPlayDialog():
    r"""
    >>> UnableToPlayDialog(frame=f("New box/Video Store/Unable to Play.png"))
    UnableToPlayDialog(is_visible=True)
    """
    pass
