#!/usr/bin/env python
# coding=utf-8
"""
This file contains regression tests automatically generated by
``stbt auto-selftest``. These tests are intended to capture the
behaviour of Frame Objects (and other helper functions that operate on
a video-frame). Commit this file to git, re-run ``stbt auto-selftest``
whenever you make a change to your Frame Objects, and use ``git diff``
to see how your changes affect the behaviour of the Frame Object.

NOTE: THE OUTPUT OF THE DOCTESTS BELOW IS NOT NECESSARILY "CORRECT" --
it merely documents the behaviour at the time that
``stbt auto-selftest`` was run.
"""
# pylint: disable=line-too-long

import os
import sys

sys.path.insert(0, os.path.join(
    os.path.dirname(__file__), '../../../tests'))

from video_store import *  # isort:skip pylint: disable=wildcard-import, import-error

_FRAME_CACHE = {}


def f(name):
    img = _FRAME_CACHE.get(name)
    if img is None:
        import cv2
        filename = os.path.join(os.path.dirname(__file__),
                                '../../screenshots', name)
        img = cv2.imread(filename)
        assert img is not None, "Failed to load %s" % filename
        img.flags.writeable = False
        _FRAME_CACHE[name] = img
    return img


def auto_selftest_Asset():
    r"""
    >>> Asset(frame=f("Worldbox/Video Store/Asset - Moonlight - Rent.png"))
    Asset(is_visible=True, rentable=True, selected_button=SelectedButton(is_visible=True, text=u'RENT $2.99'), title=u'Moonlight')
    >>> Asset(frame=f("Worldbox/Video Store/Asset - Moonlight - Restart.png"))
    Asset(is_visible=True, rentable=False, selected_button=SelectedButton(is_visible=True, text=u'RESTART'), title=u'Moonlight')
    >>> Asset(frame=f("Worldbox/Video Store/Asset - Moonlight - Watch.png"))
    Asset(is_visible=True, rentable=False, selected_button=SelectedButton(is_visible=True, text=u'WATCH'), title=u'Moonlight')
    >>> Asset(frame=f("Worldbox/Video Store/Asset - Rogue One.png"))
    Asset(is_visible=True, rentable=True, selected_button=SelectedButton(is_visible=True, text=u'RENT $2.99'), title=u'Rogue One: A Star Wars Story')
    """
    pass


def auto_selftest_ConfirmRentalDialog():
    r"""
    >>> ConfirmRentalDialog(frame=f("Worldbox/Video Store/Confirm Rental - Cancel.png"))
    ConfirmRentalDialog(is_visible=True, selection=u'CANCEL')
    >>> ConfirmRentalDialog(frame=f("Worldbox/Video Store/Confirm Rental - Confirm.png"))
    ConfirmRentalDialog(is_visible=True, selection=u'CONFIRM')
    """
    pass


def auto_selftest_SelectedButton():
    r"""
    >>> SelectedButton(frame=f("New box/Video Store/Unable to Play.png"))
    SelectedButton(is_visible=True, text=u'OK')
    >>> SelectedButton(frame=f("Worldbox/Video Store/Asset - Moonlight - Rent.png"))
    SelectedButton(is_visible=True, text=u'RENT $2.99')
    >>> SelectedButton(frame=f("Worldbox/Video Store/Asset - Moonlight - Restart.png"))
    SelectedButton(is_visible=True, text=u'RESTART')
    >>> SelectedButton(frame=f("Worldbox/Video Store/Asset - Moonlight - Watch.png"))
    SelectedButton(is_visible=True, text=u'WATCH')
    >>> SelectedButton(frame=f("Worldbox/Video Store/Asset - Rogue One.png"))
    SelectedButton(is_visible=True, text=u'RENT $2.99')
    >>> SelectedButton(frame=f("Worldbox/Video Store/Confirm Rental - Cancel.png"))
    SelectedButton(is_visible=True, text=u'CANCEL')
    >>> SelectedButton(frame=f("Worldbox/Video Store/Confirm Rental - Confirm.png"))
    SelectedButton(is_visible=True, text=u'CONFIRM')
    """
    pass


def auto_selftest_UnableToPlayDialog():
    r"""
    >>> UnableToPlayDialog(frame=f("New box/Video Store/Unable to Play.png"))
    UnableToPlayDialog(is_visible=True)
    """
    pass


def auto_selftest_VideoStore():
    r"""
    >>> VideoStore(frame=f("Worldbox/Video Store/Top Picks - Rogue One.png"))
    VideoStore(is_visible=True, selection=u'Rogue One: A Star Wars Story')
    >>> VideoStore(frame=f("Worldbox/Video Store/Top Picks - Toy Gun.png"))
    VideoStore(is_visible=True, selection=u'Toy Gun')
    """
    pass
