def test_launch_methods():
    init()
    menu_launch()
    guide_launch()
    miniguide_launch()
    my_library_launch()
    tv_shows_launch()
    movies_launch()
    video_store_launch()
    settings_launch()
